files:
  - source: /doc/index.html.in
    translation: /doc/%two_letters_code%/index.html.in
  - source: /templates/*.tmpl
    translation: /templates/%two_letters_code%/%original_file_name%
  - source: /locale/cups_en.po
    translation: /locale/cups_%two_letters_code%.po
